/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Season, SeasonInterface } from "../Season";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "int32",
        name: "id",
        type: "int32",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "initNewSeason",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101ab806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063fd943bbf14610030575b600080fd5b61004361003e366004610073565b610045565b005b505050565b803573ffffffffffffffffffffffffffffffffffffffff8116811461006e57600080fd5b919050565b600080600060608486031215610087578283fd5b83358060030b8114610097578384fd5b9250602084013567ffffffffffffffff808211156100b3578384fd5b818601915086601f8301126100c6578384fd5b8135818111156100d8576100d8610146565b604051601f8201601f19908116603f0116810190838211818310171561010057610100610146565b81604052828152896020848701011115610118578687fd5b8260208601602083013791820160200195909552935061013d9150506040850161004a565b90509250925092565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fdfea26469706673582212206f14612db2cc1b39806c990ccc20595e3f5e85b5279417dbb27f3d494bc8302c64736f6c63430008010033";

export class Season__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Season> {
    return super.deploy(overrides || {}) as Promise<Season>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Season {
    return super.attach(address) as Season;
  }
  connect(signer: Signer): Season__factory {
    return super.connect(signer) as Season__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SeasonInterface {
    return new utils.Interface(_abi) as SeasonInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Season {
    return new Contract(address, _abi, signerOrProvider) as Season;
  }
}
